# Generated by Django 4.2.2 on 2024-07-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_key_ingredients_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_size_in_milliliters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('cleanser', 'Cleanser'), ('moisturizer', 'Moisturizer'), ('night cream', 'Night Cream'), ('serum', 'Serum'), ('toner', 'Toner'), ('mask', 'Mask'), ('sunscreen', 'Sunscreen'), ('eye cream', 'Eye Cream'), ('other', 'Other')], max_length=20),
        ),
    ]
